# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ardvark < Formula
  desc "Crawler and indexer for ARD (Agentic Resource Discovery) ai-catalog.json documents"
  homepage "https://ardvark.no"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/helgesverre/ardvark/releases/download/v0.1.0/ardvark-0.1.0-darwin-amd64.tar.gz"
      sha256 "318a6f8c90822a1f47a27a8bee429027894698be524226653c4385583d1837c4"

      define_method(:install) do
        bin.install "ardvark"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/helgesverre/ardvark/releases/download/v0.1.0/ardvark-0.1.0-darwin-arm64.tar.gz"
      sha256 "4a19c99d6524c5cbf2bc01537bdeb57638994c25a186b8da3c16414ba1663499"

      define_method(:install) do
        bin.install "ardvark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/helgesverre/ardvark/releases/download/v0.1.0/ardvark-0.1.0-linux-amd64.tar.gz"
      sha256 "ed89efd4d4f9dc102e448745421acc83a7675de914990ffd6287db7f7bfb4a5f"
      define_method(:install) do
        bin.install "ardvark"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/helgesverre/ardvark/releases/download/v0.1.0/ardvark-0.1.0-linux-arm64.tar.gz"
      sha256 "00f309abb284599728ae592ba5006e7638da4e47273a03c5914aa5289156c198"
      define_method(:install) do
        bin.install "ardvark"
      end
    end
  end

  test do
    assert_match "ardvark", shell_output("#{bin}/ardvark --version")
  end
end
